# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9639ac6b95533bd225179248e1af96cc13dc1b194b1a1e4db46b0e10961b58dbc44d04df4d80a42859d4632b6afb056ab621c165c76f297180cc0e71afecf8ff

test:
  secret_key_base: 8252fbb3f20cdd185683a65910dc8cb95020eec31c1bafb357f20cfb58dafa3199adec6f0b28feb2bb35f99d95a3dd5c27fef563baffd13bc6265d32574d879a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
